server:
  port: 8083
logging:
  level:
    cn.itcast: debug
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos地址
#      username: nacos
#      password: nacos
      config:
        file-extension: yaml     # 文件后缀名
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://user-service # 127.0.0.1:8084 # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/login/**  # 路径断言，判断路径是否是以/user开头，如果是则符合
        - id: good-service
          uri: lb://good-service
          predicates:
            - Path=/order/**
        - id: seckill-service
          uri: lb://sekill-service # 127.0.0.1:8084
          predicates:
            - Path=/seckill/**
          filters:
            # 配置令牌桶
            - name: RequestRateLimiter
          args:
            # 如果keyResolver返回空key，则拒绝该请求403，默认true表示拒绝，false则表示允许访问
            deny-empty-key: false
            # 配置类：RateLimiter 实现类 RedisRateLimiter 对象
            redis-rate-limiter:
              # 自定义一个 keyResolver 实现 KeyResolver MyKeyResolver,注入容器,使用Spring的EL表达式读取值
              key-resolver: "#{@myKeyResolver}"
              redis-rate-limiter:
                replenishRate: 40 # 每秒生成令牌个数
                burstCapacity: 200 # 令牌桶上线容量
      #default-filters: AuthGlobalFilter

  # 令牌桶使用到 Redis ,需要配置Redis连接属性
  redis:
    #服务器地址
    host: 127.0.0.1
    #端口
    port: 6379
    #数据库编号
    database: 1
    #超时时间
    timeout: 10000ms
    #密码
    #    password: root
    lettuce:
      pool:
        #最大连接数，默认8
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 5

gateway:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800   #7天
    header: Authorization