#wechat:
#  pay:
#    v3:
#      #    租户id
#      <tentantID>:
#        #  应用appId  服务商模式下为服务商的appid 必填
#        app-id: xxxxxxxx
#        #  v2 api 密钥  1.0.5版本以后如果用到V2的接口时必填
#        app-secret: xxxxxxxxxxx
#        #  api v3 密钥 必填
#        app-v3-secret: xxxxxxxx
#        #  微信支付商户号 服务商模式下为服务商的mchid 必填
#        mch-id: xxxxxxx
#        #  商户服务器域名 用于回调  需要放开回调接口的安全策略 必填
#        domain: https://felord.cn
#        #  商户 api 证书路径 必填  填写classpath路径 位于 maven项目的resources文件下
#        cert-path: apiclient_cert.p12
# 微信支付，以下参数均为虚构
wechat:
  pay:
    v3:
      # 租户tentanID的id # 自动扫描配置文件，把对应的id和自动补全回调ip+端口
      mobile:
        # 应用appId 必填
        app-id: wx74862e0dfcf69954
        # v2 api 密钥  1.0.5版本以后如果用到V2的接口时必填，单纯V3不需要
        app-secret: felordcn
        # api v3 密钥 必填
        app-v3-secret: UDuLFDcmy5Eb6o0nTNZdu6ek4DDh4K8B
        # 微信支付商户号 必填
        mch-id: 1558950191
        # 商户服务器域名 用于回调  回调路径为 domain + notifyUrl  需要放开回调接口的安全策略 必填
        domain: https://7d92-115-171-63-135.ngrok.io
        # 商户 api 证书路径 必填  填写classpath路径 位于 maven项目的resources文件下
        cert-path: wechat/apiclient_cert.p12
